### ISSUE TITLE
Map deprecated language codes to modern equivalents

### ISSUE THREAD

**Issue by 1ec5** [mapbox/locale-utils#4]
The following ISO&nbsp;639:1988 codes were deprecated 21 years ago, but Android’s `Locale.getLanguage()` method [still returns them](https://developer.android.com/reference/java/util/Locale.html#special_cases_constructor):

* `iw` for Hebrew, replaced by `he`
* `ji` for Yiddish, replaced by `yi`
* `in` for Indonesian, replaced by `id`

This library should map the deprecated codes to the standard ISO 639-1 equivalents, so that Android developers who interact with an API that uses this library don’t have to worry about these otherwise obscure codes.

/cc @bsudekum @danesfeder @devotaaabel @danpaz @Guardiola31337

**Comment by 1ec5** [comment]
Several ISO&nbsp;639 identifiers, such as `mo`/`mol`, have been deprecated as well, but I’m unaware of any operating systems that prefer them over the standard identifiers. #1 would be a more effective way of increasing ISO&nbsp;639 coverage.

**Comment by bsudekum** [comment]
👍 , I think it'd be fair to handle deprecated locales here.

**Comment by bsudekum** [comment]
@1ec5 on second thought, this library does not have any concern to the locales passed into it. I think this ticket needs to be moved elsewhere.

**Comment by 1ec5** [comment]
While it is the case that the client has to pass in the available language codes and the code to match, this library should be responsible for knowing that `he` and `iw` are synonymous. For example, `locale.bestMatchingLocale('iw', ['he']))` should return `true`, but it currently returns `false`.

**Comment by bsudekum** [comment]
Okay, that makes sense.
