### ISSUE TITLE
Fallback from Arabic to Modern Standard Arabic

### ISSUE THREAD

**Issue by 1ec5** [mapbox/locale-utils#9]
The Mapbox Navigation SDKs [for Android](https://docs.mapbox.com/android/navigation/overview/localization/#custom-language) and [iOS](https://docs.mapbox.com/ios/navigation/overview/localization-and-internationalization/#supported-languages) claim to support spoken instructions in Arabic and automatically request Arabic instructions if the application is being presented to the user in Arabic.

Every operating system including Android and iOS uses ISO&nbsp;639’s inclusive code `ar` (or `ara`) to represent Arabic, and so does [OSRM Text Instructions](https://github.com/Project-OSRM/osrm-text-instructions/blob/master/languages/translations/ar.json). Unfortunately, the Mapbox Voice API ([via Amazon Polly](https://docs.aws.amazon.com/polly/latest/dg/voicelist.html)) uses the more specific code `arb`, which technically represents only Modern Standard Arabic. This discrepancy reflects Polly’s focus on spoken language varieties versus OSRMTI’s focus on written varieties.

As with #7, there may need to be fallbacks in both directions to ensure interoperability.

/cc @mapbox/navigation-ios @mapbox/navigation-android @mapbox/language @danpaz

**Comment by browndp08** [comment]
@1ec5 does the following test capture what you would expect to see as a fix for this issue?
```
t.equal(locale.bestMatchingLocale('ar', valhalla_language_codes), 'ar-AE')
t.equal(locale.bestMatchingLocale('ar', polly_language_codes), 'arb')
```

As I understand it, these would also need to be added to [api-valhalla](https://github.com/mapbox/api-valhalla/blob/ca143a1f51e2ec83a68c34fbfda2ab13150e5b63/src/constants.js#L476).

Note: [valhalla ar-AE](https://github.com/mapbox/valhalla-internal/blob/master/locales/ar-AE.json)
[Polly arb](https://docs.aws.amazon.com/polly/latest/dg/SupportedLanguage.html)

**Comment by 1ec5** [comment]
The first fallback already works, assuming `valhalla_language_codes` contains `ar-AE` but not `ar` or any other `ar-*`. (This package is written generically so that it can’t assume the UAE is the default region for Arabic.)

The second fallback is what’s tracked by this issue.
